# Generated by Django 5.2.5 on 2025-08-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vállalkozás neve')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('address', models.CharField(max_length=300, verbose_name='Cím')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Weboldal')),
                ('logo', models.ImageField(blank=True, upload_to='business_logos/', verbose_name='Logó')),
                ('monday_open', models.TimeField(blank=True, null=True, verbose_name='Hétfő nyitás')),
                ('monday_close', models.TimeField(blank=True, null=True, verbose_name='Hétfő zárás')),
                ('tuesday_open', models.TimeField(blank=True, null=True, verbose_name='Kedd nyitás')),
                ('tuesday_close', models.TimeField(blank=True, null=True, verbose_name='Kedd zárás')),
                ('wednesday_open', models.TimeField(blank=True, null=True, verbose_name='Szerda nyitás')),
                ('wednesday_close', models.TimeField(blank=True, null=True, verbose_name='Szerda zárás')),
                ('thursday_open', models.TimeField(blank=True, null=True, verbose_name='Csütörtök nyitás')),
                ('thursday_close', models.TimeField(blank=True, null=True, verbose_name='Csütörtök zárás')),
                ('friday_open', models.TimeField(blank=True, null=True, verbose_name='Péntek nyitás')),
                ('friday_close', models.TimeField(blank=True, null=True, verbose_name='Péntek zárás')),
                ('saturday_open', models.TimeField(blank=True, null=True, verbose_name='Szombat nyitás')),
                ('saturday_close', models.TimeField(blank=True, null=True, verbose_name='Szombat zárás')),
                ('sunday_open', models.TimeField(blank=True, null=True, verbose_name='Vasárnap nyitás')),
                ('sunday_close', models.TimeField(blank=True, null=True, verbose_name='Vasárnap zárás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Vállalkozás',
                'verbose_name_plural': 'Vállalkozások',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Szolgáltatás neve')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('duration', models.PositiveIntegerField(verbose_name='Időtartam (perc)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Ár (Ft)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Szolgáltatás',
                'verbose_name_plural': 'Szolgáltatások',
                'ordering': ['name'],
            },
        ),
    ]
