# Generated by Django 5.2.5 on 2025-08-15 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'business_admin'}, related_name='managed_businesses', to=settings.AUTH_USER_MODEL, verbose_name='Admin felhasználók'),
        ),
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business', verbose_name='Vállalkozás'),
        ),
    ]
