# Generated by Django 5.2.5 on 2025-08-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Ügyfél neve')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Ügyfél e-mail')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Ügyfél telefon')),
                ('status', models.CharField(choices=[('pending', 'Függőben'), ('confirmed', 'Megerősítve'), ('completed', 'Befejezve'), ('cancelled', 'Lemondva')], default='pending', max_length=20, verbose_name='Státusz')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Teljes ár (Ft)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Foglalás',
                'verbose_name_plural': 'Foglalások',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dátum')),
                ('start_time', models.TimeField(verbose_name='Kezdő időpont')),
                ('end_time', models.TimeField(verbose_name='Befejező időpont')),
                ('is_available', models.BooleanField(default=True, verbose_name='Elérhető')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
            ],
            options={
                'verbose_name': 'Időpont',
                'verbose_name_plural': 'Időpontok',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
